[package]
name = "controls"
version = "0.1.0"
edition = "2021"

[dependencies]
async-graphql = "7.0.13"
async-graphql-axum = "7.0.13"
axum = "0.8.1"
serde = { version="1.0.217", features= ["derive"] }
serde_json = "1.0.135"
tokio = { version="1.43.0", features = ["full"] }
